//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace ACMEWorker
{
}

namespace ACMEWorker
{
}

namespace ACMEWorker
{
}

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/DataSet1.xsd", IsNullable=false)]
public partial class DataSet1
{
    partial class Post1DataTable
    {
    }

    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Address", typeof(DataSet1Address))]
    [System.Xml.Serialization.XmlElementAttribute("Album", typeof(DataSet1Album))]
    [System.Xml.Serialization.XmlElementAttribute("Comment", typeof(DataSet1Comment))]
    [System.Xml.Serialization.XmlElementAttribute("Company", typeof(DataSet1Company))]
    [System.Xml.Serialization.XmlElementAttribute("Photo", typeof(DataSet1Photo))]
    [System.Xml.Serialization.XmlElementAttribute("Post", typeof(DataSet1Post))]
    [System.Xml.Serialization.XmlElementAttribute("Todo", typeof(DataSet1Todo))]
    [System.Xml.Serialization.XmlElementAttribute("User", typeof(DataSet1User))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1Address {
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string streetField;
    
    private string suiteField;
    
    private string cityField;
    
    private string zipcodeField;
    
    private string geoLatField;
    
    private string geoLngField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string suite {
        get {
            return this.suiteField;
        }
        set {
            this.suiteField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string zipcode {
        get {
            return this.zipcodeField;
        }
        set {
            this.zipcodeField = value;
        }
    }
    
    /// <remarks/>
    public string geoLat {
        get {
            return this.geoLatField;
        }
        set {
            this.geoLatField = value;
        }
    }
    
    /// <remarks/>
    public string geoLng {
        get {
            return this.geoLngField;
        }
        set {
            this.geoLngField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1Album {
    
    private int userIDField;
    
    private bool userIDFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string titleField;
    
    /// <remarks/>
    public int userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIDSpecified {
        get {
            return this.userIDFieldSpecified;
        }
        set {
            this.userIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1Comment {
    
    private int postIDField;
    
    private bool postIDFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string nameField;
    
    private string emailField;
    
    private string bodyField;
    
    /// <remarks/>
    public int postID {
        get {
            return this.postIDField;
        }
        set {
            this.postIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool postIDSpecified {
        get {
            return this.postIDFieldSpecified;
        }
        set {
            this.postIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1Company {
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string nameField;
    
    private string catchPhraseField;
    
    private string bsField;
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string catchPhrase {
        get {
            return this.catchPhraseField;
        }
        set {
            this.catchPhraseField = value;
        }
    }
    
    /// <remarks/>
    public string bs {
        get {
            return this.bsField;
        }
        set {
            this.bsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1Photo {
    
    private int albumIDField;
    
    private bool albumIDFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string titleField;
    
    private string urlField;
    
    private string thumbnailUrlField;
    
    /// <remarks/>
    public int albumID {
        get {
            return this.albumIDField;
        }
        set {
            this.albumIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool albumIDSpecified {
        get {
            return this.albumIDFieldSpecified;
        }
        set {
            this.albumIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string thumbnailUrl {
        get {
            return this.thumbnailUrlField;
        }
        set {
            this.thumbnailUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1Post {
    
    private int userIDField;
    
    private bool userIDFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string titleField;
    
    private string bodyField;
    
    /// <remarks/>
    public int userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIDSpecified {
        get {
            return this.userIDFieldSpecified;
        }
        set {
            this.userIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1Todo {
    
    private int userIDField;
    
    private bool userIDFieldSpecified;
    
    private int idField;
    
    private bool idFieldSpecified;
    
    private string titleField;
    
    private bool completedField;
    
    private bool completedFieldSpecified;
    
    /// <remarks/>
    public int userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIDSpecified {
        get {
            return this.userIDFieldSpecified;
        }
        set {
            this.userIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public bool completed {
        get {
            return this.completedField;
        }
        set {
            this.completedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool completedSpecified {
        get {
            return this.completedFieldSpecified;
        }
        set {
            this.completedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/DataSet1.xsd")]
public partial class DataSet1User {
    
    private int userIDField;
    
    private bool userIDFieldSpecified;
    
    private string nameField;
    
    private string usernameField;
    
    private string emailField;
    
    private int addressField;
    
    private bool addressFieldSpecified;
    
    private int companyField;
    
    private bool companyFieldSpecified;
    
    /// <remarks/>
    public int userID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userIDSpecified {
        get {
            return this.userIDFieldSpecified;
        }
        set {
            this.userIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public int address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool addressSpecified {
        get {
            return this.addressFieldSpecified;
        }
        set {
            this.addressFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public int company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool companySpecified {
        get {
            return this.companyFieldSpecified;
        }
        set {
            this.companyFieldSpecified = value;
        }
    }
}
